## Task1

In [1]:
import numpy as np

In [7]:
A = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
A = A.transpose()

In [9]:
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
mean_a = A.mean(axis = 0)
mean_a

array([2. , 8.4])

## Task2

In [19]:
# Используем broadcasting
a_centered = A - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Task3

In [20]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [21]:
a_centered_sp / (len(a_centered) - 1)

2.0

## Task4

In [22]:
np.cov(A.T)

array([[1. , 2. ],
       [2. , 4.3]])